Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 30000000
  llc_capacity_per_core: 1KB # Should be set as no cache, but this is a workaround
  # YAML expects the following format for the traces, which is a trace_list
  traces:
    - /root/user/3D_DRAM_MODELING_MASTER/ramulator2/traces/marching_pattern_1Gb.trace
    # - /root/user/traces/high-mem-intensity.trace
    # - /root/user/3D_DRAM_MODELING_MASTER/ramulator2/traces/high-mem-intensity.trace

  # Translation:
  #   impl: RandomTranslation
  #   max_addr: 2199015689679

  Translation:
    impl: NoTranslation
    max_addr: 134217728

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: DDR4

    drampower_enable: true # This can enable dram power model
    structure_type: 1
    # The preset of DRAM voltage and current must be specified, also the preset for power modeling has to exists within.
    voltage:
      preset: Default # Sets to Default to enable basic voltage adjustment
    current:
      preset: Default

    org:
      preset: DDR4_1Gb_x128
      # channel_width: 128
      # preset: DDR4_2Gb_x4
      channel: 1
      rank: 1
    timing:
      preset: DDR4_3DDRAM_128

  Controller:
    impl: Generic
    Scheduler:
      impl: FCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:
      - ControllerPlugin:
          impl: CommandCounter
          path: ./cmd_records/1Gb_1ch.cmds
          commands_to_count:
            - REFab

  AddrMapper:
    impl: ChRaBaRoCo